name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_EVENT_NAME: ${{ github.event_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.12"
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install git+https://github.com/laminlabs/laminci
      - run: uv pip install --system -e .[scdataset]
      # will consolidate installation in next refactor once this is merged: https://github.com/laminlabs/lamindb/pull/2976
      - run: uv pip install --system git+https://github.com/laminlabs/arrayloaders
      - run: uv pip install --system zarrs  # needed until arrayloaders is updated to use zarr>=2.20.0
      - run: lamin init
      - run: |
          python -c "
          import lamindb as ln
          ln.Project(name='Arrayloader benchmarks v2').save()
          "
      - run: python scripts/run_data_loading_benchmark_on_tahoe100m.py annbatch
